### ISSUE TITLE
use standard log4j configuration

### ISSUE THREAD

**Issue by michaelwittig** [taimos/daemon-framework#14]
org.apache.log4j.PropertyConfigurator would allow users to use their own logging configuration and is very common

**Comment by alph486** [comment]
What about [SLF4J](http://www.slf4j.org/)? Might be a good integration point for those using different frameworks.

**Comment by hoegertn** [comment]
I think slf4j is a good solution to be used in frameworks and libraries used in your app. But I see the daemon framework as the basic building block that is doing the real wiring to a log mechanism and configuring the whole logging setup. Configuring log4j is a big part of the daemon framework. But it might be worth splitting this in two parts and to extract the log4j part using some interfaces.

**Comment by hoegertn** [comment]
Done in major rework on master (2.0-SNAPSHOT)
