### ISSUE TITLE
implement Docker friendly lifecycle

### ISSUE THREAD

**Issue by hoegertn** [taimos/daemon-framework#15]

**Comment by guedressel** [comment]
What is a docker friendly lifecycle?

**Comment by hoegertn** [comment]
I plan to implement a secondary startup mode which logs to console instead of files, has a slightly different signal handling and to provide a startup script which does not daemonize but can be used as CMD in a Dockerfile.

Any further ideas are welcome.

**Comment by guedressel** [comment]
Docker friendly lifecycle == run daemon in foreground
got it. sounds quite useful - even without Docker.

**Comment by hoegertn** [comment]
environments using systemd might use the same enhancements. But I will have a deeper look at systemd before.
